version: "3.9"

services:
  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile.dev
    container_name: nozorin_ui
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/app         
      - /app/node_modules   
    env_file:
      - ./ui/.env
    depends_on:
      - api
      - realtime

  api:
    build:
      context: .
      dockerfile: api/Dockerfile.dev
    container_name: nozorin_api
    ports:
      - "3001:3001"
    volumes:
      - ./api:/app
      - /app/node_modules
    env_file:
      - ./api/.env
    depends_on:
      - db
      - redis
      - realtime

  realtime:
    build:
      context: .
      dockerfile: socket/Dockerfile.dev
    container_name: nozorin_realtime
    ports:
      - "3002:3002"
    volumes:
      - ./socket:/app
      - /app/node_modules
    env_file:
      - ./socket/.env
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    container_name: nozorin_db
    restart: always
    environment:
      MYSQL_DATABASE: nozorin_db
      MYSQL_USER: nozorin
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: nozorin_redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: root
    command: sh -c "redis-server --requirepass $${REDIS_PASSWORD}"

volumes:
  mysql_data: